version: "3.7"

services:
  git:
    image: alpine/git
    entrypoint: "sh /entrypoint.sh"
    configs:
      - source: conveyor_sync_prd_git_puller
        target: /entrypoint.sh
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - server_data:/git/m-backend
      - web_data:/git/m-web
    networks:
      - public_proxy
  mongo:
    image: mongo:4
    volumes:
      - mongo_data:/data/db
    #entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--auth"]
    ports:
      - 3057:27017
  redis:
    image: redis:5
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  server:
    image: node:lts-alpine
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      JWT_SECRET: ${JWT_SECRET}
      WORKER_HOST: ${WORKER_HOST}
      WORKER_PORT: ${WORKER_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TYPEORM_CONNECTION: ${TYPEORM_CONNECTION}
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      TYPEORM_PORT: ${TYPEORM_PORT}
      TYPEORM_LOGGING: ${TYPEORM_LOGGING}
      API_DOCS_URI: ${API_DOCS_URI}
      API_DOCS_TITLE: ${API_DOCS_TITLE}
      API_DOCS_DESCRIPTION: ${API_DOCS_DESCRIPTION}
      API_DOCS_VERSION: ${API_DOCS_VERSION}
      API_DOCS_TAG: ${API_DOCS_TAG}
    command: "sh -c 'cd /app/server && cp -f env.prd .env && ls -la && yarn install --production=false && yarn run build && yarn start'"
    volumes:
      - server_data:/app
    ports:
      - "3050:4000"
    networks:
      - default
      - public_proxy
      - public_api_gateway
  web:
    image: node:lts
    environment:
      NODE_ENV: production
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      REACT_APP_GRAPH_ENDPOINT: ${REACT_APP_GRAPH_ENDPOINT}
      REACT_APP_GRAPH_WS_ENDPOINT: ${REACT_APP_GRAPH_WS_ENDPOINT}
    command: "sh -c 'cd /app && ls -la && yarn install --production=false && rm -rf build && mkdir build && yarn build-app && npx serve -s build --no-clipboard'"
    volumes:
      - web_data:/app
    ports:
       - 3055:5000
configs:
  conveyor_sync_prd_git_puller:
    external: true

networks:
  public_api_gateway:
    external: true
  public_proxy:
    external: true

volumes:
  mongo_data:
  redis_data:
  server_data:
  web_data: