version: "3.7"

services:
  mongo:
    image: mongo:4.2
    restart: always
    volumes:
      - mongo_data:/data/db
    #entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--auth"]
    ports:
      - 5004:27017
  rabbitmq:
    restart: always
    image: rabbitmq:alpine
    ports:
      - 5002:5672
      - 5003:15672
    volumes:
      - ./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins
    environment:
        TZ: Asia/Ho_Chi_Minh
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASS: rabbitmq
  mysql:  
    image: mysql:8
    restart: always
    command: ["--default-authentication-plugin=mysql_native_password", "--bind-address=0.0.0.0"]
    ports:
      - 5005:3306
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: default 
    ports:
      - 5007:80
  redis:
    restart: always
    image: redis:5
    command: ["sh", "-c", "exec redis-server --appendonly yes --requirepass 'redis_pass'"]
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: redis_pass
    ports:
      - 5006:6379

volumes:
  mysql_data:
  redis_data:
  mongo_data:

