version: "3.7"

services:
  app:
    image: registry.tn20.wedesign.vn/inventory:latest
    depends_on:
      - mysql     
    environment:
      ENV_FOR_DYNACONF: ''
      SENTRY_DSN: ${SENTRY_DSN}
      DATABASE_URL: ${DATABASE_URL}
      GUNICORN_THREADS: ${GUNICORN_THREADS}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
    deploy:
      replicas: 1    
      restart_policy:
        condition: on-failure
  mysql:  
    image: mysql:8
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 9004:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:      
      restart_policy:
        condition: on-failure
  redis:
    image: redis:5
    command: ["sh", "-c", "exec redis-server --appendonly no --requirepass \"$REDIS_PASSWORD\""]
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 9005:6379

networks:
  public_proxy:
    external: true

volumes:
  mysql_data:
  redis_data:

  