version: "3.7"

services:
  app:
    image: registry.tn20.wedesign.vn/inventory:latest
    depends_on:
      - mysql     
    environment:
      ENV_FOR_DYNACONF: ''
      SENTRY_DSN: ${SENTRY_DSN}
      DATABASE_URL: ${DATABASE_URL}
      GUNICORN_THREADS: ${GUNICORN_THREADS}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
    deploy:
      replicas: 1    
      restart_policy:
        condition: on-failure
    networks:
      - common_network
networks:
  common_network:
    external: true

  